### PR TITLE
Updating version of protobufjs dependency

### PR DESCRIPTION
**Pull request by herbrandson**
According to `npm audit`, the version of protobufjs being used by this package has a security vulnerability (see output below). This PR simply updates the version of protobufjs in package.json from `6.7.3` to `^6.8.6`. All unit tests still pass. Also, please note the use of a caret (`^`)  in the version number. I'm not sure if there was a reason for pinning to a specific version of protobufjs or not, but generally using the caret is preferred.

```
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ protobufjs                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.0.3 < 6.0.0 || >=6.8.6                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gtfs-realtime-bindings                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gtfs-realtime-bindings > protobufjs                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/605                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### CODE REVIEW

**Comment by herbrandson** [comment]
*ping*

**Comment by herbrandson** [comment]
ping

**Comment by barbeau** [comment]
Thanks @herbrandson!  I changed back to pinning the exact version to avoid non-deterministic behavior from versions automatically updating themselves (resulting in the CLA comment above).

**Comment by barbeau** [comment]
Closing this as a duplicate of https://github.com/google/gtfs-realtime-bindings/pull/42, which is easier to merge due to CLA issues.

**Pull request closed without merging**
