### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by robbiet480**
This updates `gtfs_realtime_pb2.py` to be compatible with Python 3 by using Protocol Buffers [version 3](https://github.com/google/protobuf/releases/tag/v3.0.0). I also changed the README.md example to use the [requests](http://docs.python-requests.org/en/master/) library instead of urllib since requests is Python 2.x/3 compatible. Finally, I bumped the package version from 0.0.4 to 0.0.5.

Related issue: #17

### CODE REVIEW

**Comment by robbiet480** [comment]
I signed it!

**Comment by egorich239** [comment]
1. GTFS RT is protobuf2
2. Does your change (import requests) break python2? it should not

**Comment by robbiet480** [comment]
@egorich239 Protobuf is now at version 3. Version 2 is still supported and "will be for a long time" according to the version 3 release notes [here](https://github.com/google/protobuf/releases/tag/v3.0.0). Protobuf version 3 provides Python 2.x and 3.x support while also continuing support for Protobuf 2.

**Comment by egorich239** [comment]
@robbiet480 What I mean is protobuf3 is not a drop in replacement for protobuf2 -- it has a lot of semantics changes. GTFS RT is designed on top of protobuf2 semantics.

**Comment by robbiet480** [comment]
@egorich239 I understand. Protobuf 3 continues to support working with Protobuf 2, meaning that I used the `protoc` from Protobuf 3 to generate a new `gtfs_realtime_pb2.py` which is Python 2.x/3.x compatible while still being Protobuf 2.

**Comment by robbiet480** [comment]
Actually it even specifies in the new `gtfs_realtime_pb2.py` that it is `proto2` [here](https://github.com/google/gtfs-realtime-bindings/pull/20/files#diff-7ae2db0d1fcd6f76a52214a6ad86efc1R37).

**Comment by robbiet480** [comment]
@egorich239 Thanks! :cookie:

**Comment by robbiet480** [comment]
@egorich239 Can someone push the latest version to PyPi?

**Comment by robbiet480** [comment]
Bumping this in the hopes of having the latest version pushed to PyPi.

**Comment by robbiet480** [comment]
Fixes #17

**Comment by joovel** [comment]
Come on, can we have a new version on pypi, please? This is ridiculous.

**Comment by robbiet480** [comment]
@RachM can you release a new version to PyPI?

**Comment by RachM** [comment]
Yup, I've commented on [issue 21](https://github.com/google/gtfs-realtime-bindings/issues/21). Will post updates there.

**Pull request merged**
